# https://github.com/flant/loghouse/issues/28#issuecomment-349274259
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: jenkins
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""